### ISSUE TITLE
Loot generation for ruined portal

### ISSUE THREAD

**Issue by Snowad14** [jellejurre/seed-checker#2]
Seed-Checker finds the right chests locations but does not generate the right loots (maybe because of the portal rotation?)
Tested in 1.18 but I think the other versions have the same bug

**Comment by jellejurre** [comment]
Seems to work fine for me

1.18.1, Seed 1, Location 300, 71, 290

This code: 
```
        SeedChecker checker = new SeedChecker(1l);
        List<ItemStack> list = checker.generateChestLoot(300, 71, 290);
        list.forEach(x -> System.out.println(x.getItem().getName().getString() + "|" + x.getCount() + "|" + x.getEnchantments().size()));
```

Gives me this output: 

Light Weighted Pressure Plate|1|0
Gold Nugget|19|0
Gold Ingot|3|0
Golden Sword|1|1
Obsidian|1|0
Golden Apple|1|0

Which is exactly what is in that chest. 

Can you give an example where the loot generation goes wrong?

**Comment by Snowad14** [comment]
my bad, I wouldn't have believed that the 1.18.1 and 1.18.2 generation were different, thanks.
![image](https://user-images.githubusercontent.com/67842535/179840953-c2d6fb80-60ba-4928-83f5-fda21e99ecb4.png)
![image](https://user-images.githubusercontent.com/67842535/179841044-fbc78cc0-3421-4946-9ed7-921e4b88d7a5.png)
